
language: java
sudo: false
install: true

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "sivaprasadreddy-github"

script:
  # JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
