version: '2'

services:
  geeksclub:
    build: .
    container_name: geeksclub
    ports:
     - "18080:8080"
     - "18787:8787"
    depends_on:
      - gcmysql
      - grafana

  gcmysql:
    image: mysql:5.6.26
    container_name: gcmysql
    environment:
     - MYSQL_ROOT_PASSWORD=gcadmin
     - MYSQL_DATABASE=gcdb
     - MYSQL_USER=siva
     - MYSQL_PASSWORD=sivalabs
    ports:
      - "3316:3306"

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml

volumes:
  prometheus_data: {}
  grafana_data: {}